### ISSUE TITLE
Fancy Text Emoji issue

### ISSUE THREAD

**Issue by danmackie** [rupok/essential-addons-elementor-lite#10]
Hello!
I'm using the Fancy Text element on dev2.tentop.com. As part of the text I'm using emoji which act strangely in that when they first load they get a missing character symbol then appear after a few milliseconds. I also get an error in the console as follows:

Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://dev2.tentop.com/wp-content/plugins/essential-addons-elementor/assets/js/typed.min.js?ver=1.0
Source Map URL: typed.min.js.map

**Comment by rupok** [comment]
Hi @danmackie 

Looks like the library doesn't support this kind of emojis well. I'll see if I can do something to fix this.

Thanks!
