### ISSUE TITLE
I was just prompted to install the 2.1 

### ISSUE THREAD

**Issue by magoo6617** [rupok/essential-addons-elementor-lite#14]
Version 2.10.0 | By Codetic |

now, my EA Tabs component no longer functions.  Additionally, each time i try to create a new tab element, it fails to work correctly.

is there a way to fix or revert back to the prior release?

**Comment by magoo6617** [comment]
To confirm, it is the "EA Advanced Tabs" component

**Comment by rupok** [comment]
Hello @magoo6617

I believe you got it fixed already by hard refreshing. If not, then hard refresh your page and clear cache as we have changed some CSS.

Cheers!
