### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by alexistala** [rupok/essential-addons-elementor-lite#2]
Hello,

After installing and configuring the pluging, this is the error message I get:

> Notice: Undefined index: image-accordion in /home/wcmedia/ftp/cmfipolska.pl/enoch.cmfipolska.pl/wp-content/plugins/essential-addons-for-elementor-lite/essential_adons_elementor.php

What can I do to resolve this?

**Comment by rupok** [comment]
Hello @alexistala 

It's a new element and it's not saved on your settings. Go to **Essential Addons Elementor > Elements** and hit save button.

Thanks!
