### ISSUE TITLE
elementor panel not show all elements 

### ISSUE THREAD

**Issue by hellworks** [rupok/essential-addons-elementor-lite#219]
i have activate the plug-in essential addons for elementor, but not all of the free elements wich i have activate is show on elementor editor, why?how can i fix it?

![geyhet](https://user-images.githubusercontent.com/48483815/54207270-89ff0500-44e2-11e9-9bc3-a6dafad152d7.JPG)
![hfsh](https://user-images.githubusercontent.com/48483815/54207271-8a979b80-44e2-11e9-93e3-04c776f4c3c7.JPG)
![shrh](https://user-images.githubusercontent.com/48483815/54207272-8b303200-44e2-11e9-9df5-7ed0fa1ba266.JPG)

**Comment by rupok** [comment]
Hi @hellworks I guess you are referring the form elements. They won't appear if the dependency form plugins are not installed. For example, if you want to use "Contact Form 7 Styler" make sure you have installed Contact Form 7. Note that our widget is just helping you to style the forms, you still need the form plugins for the functionality. 

Hope this makes sense.
