### ISSUE TITLE
Lite and Pro won't work together

### ISSUE THREAD

**Issue by vuk** [rupok/essential-addons-elementor-lite#22]
When I try to activate both lite and pro versions of plugin I get this error 

    `Fatal error: Cannot redeclare eael_init() (previously declared in /var/www/html/wp-content/plugins/essential-addons-elementor/essential_adons_elementor.php:482) in /var/www/html/wp-content/plugins/essential-addons-for-elementor-lite/essential_adons_elementor.php on line 276`

But this wasn't the case before. Is this intentional or shouldn't be?

**Comment by rupok** [comment]
Hi @vuk You don't need two plugins at a time. Deactivate free and activate pro.

Cheers!
