### ISSUE TITLE
I can't activate essential addons

### ISSUE THREAD

**Issue by zzsoulas** [rupok/essential-addons-elementor-lite#220]
![error report](https://user-images.githubusercontent.com/48494902/54233121-f135ad00-4514-11e9-83e2-39dbd245778b.png)

I get this error when I try to avtivate essential addons for Elementor.

**Comment by rupok** [comment]
Hi @zzsoulas please deactivate the free version first.

**Comment by zzsoulas** [comment]
Thank you, I didn't notice that it could be the problem.
