### ISSUE TITLE
EA Flix box and text is no centralized. Why?

### ISSUE THREAD

**Issue by RitzCoworking** [rupok/essential-addons-elementor-lite#222]
Hello Git Hub Team. I recently updated the Elementor addon plugin and for some reason all the flip boxes that I use on my home page had this issue, not allowing me to centralize the text anymore. For some reason, it justified the text to the left and now I can not change it.

If you could help with this I would thank you so much.

Best regards,
Bernardo Dalla

This is a print screen of the homepage of https://ritzco.com.br:

<img width="1278" alt="Captura de Tela 2019-03-20 às 01 18 57" src="https://user-images.githubusercontent.com/48744493/54658850-38401700-4aae-11e9-8389-6ccdf83d952b.png">

**Comment by sabuz** [comment]
@RitzCoworking Hi, we have actually reached out to you through our support forum. I assume that your issue is resolved. Isn't it? I am closing the ticket as a result. Please let me know if you still have any issues. Thank you.
