### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Essential_Addons_Elementor\Traits\RGFormsModel' not foun

### ISSUE THREAD

**Issue by galwpsite** [rupok/essential-addons-elementor-lite#246]
Hi I am getting this error since updating the plugin:
Fatal error: Uncaught Error: Class 'Essential_Addons_Elementor\Traits\RGFormsModel' not found in /home/beindcom/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Helper.php:1035 Stack trace: #0 /home/beindcom/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Enqueue.php(19): Essential_Addons_Elementor->eael_select_gravity_form() #1 /home/beindcom/public_html/wp-includes/class-wp-hook.php(286): Essential_Addons_Elementor->enqueue_scripts('') #2 /home/beindcom/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #3 /home/beindcom/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /home/beindcom/public_html/wp-includes/script-loader.php(2463): do_action('wp_enqueue_scri...') #5 /home/beindcom/public_html/wp-includes/class-wp-hook.php(286): wp_enqueue_scripts('') #6 /home/beindcom/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #7 /home/beindcom/public_html/wp-includes/plugin. in /home/beindcom/public_html/wp-content/plugins/essential-addons-for-elementor-lite/includes/traits/Helper.php on line 1035

**Comment by rupok** [comment]
Hi @galwpsite 

Please deactivate and delete the plugin and then install a fresh copy.

Thanks!

**Comment by rupok** [comment]
Hi @galwpsite 

We were able to track and fix the issue. Please re-install a fresh copy now.

Cheers!
