### ISSUE TITLE
Caldera Contact Form

### ISSUE THREAD

**Issue by TheCre8tor** [rupok/essential-addons-elementor-lite#257]
I am having trouble with this plugin after i updated to the latest version of the plugin. The contact form input field became overstretched on mobile phone and became very short on desktop/laptop devices. kindly check through this link;  https://nitxdesign.com/social-media-design-bronze/

**Comment by sabuz** [comment]
Let me know if it has been fixed for you in last update.

**Comment by TheCre8tor** [comment]
@sabuz
Thank you for reaching out, 
It has been resolved.
