### ISSUE TITLE
Causing website to not showup

### ISSUE THREAD

**Issue by Akankshaparmar** [rupok/essential-addons-elementor-lite#74]
Hi,

The plugin was working fine. All of a sudden it stopped working and caused white screen of death.

Please check, I really liked the functionalities. 

Best regards
Akanksha

**Comment by rupok** [comment]
Hi there,

It could be that a fatal error is preventing the preview to load. Could you please enable the debug mode. You can do this by opening `wp-config.php` and adding :

```define('WP_DEBUG', true);```

When you revisit the page, you should have some error output describing the issue in more detail.

Let me know how it goes. 
Thanks!

**Comment by rupok** [comment]
It should be fine from recent updates.
