### ISSUE TITLE
GF Widget styling in Edit mode different than live

### ISSUE THREAD

**Issue by napa-web-designer** [rupok/essential-addons-elementor-lite#9]
When I look at my Gravity Forms form when editing with elementor, the styling is very different than it is when I have exited Elementor. For example there are bullet lists showing and spacing between fields is different when editing in Elementor, but when I have existed Elementor it looks fine.

**Comment by rupok** [comment]
Hi there,

Perhaps you have disabled Gravity Form CSS.

Thanks!

**Comment by napa-web-designer** [comment]
Nope. I just checked to confirm. Gravity Forms>Settings>Output CSS is checked Yes.

https://d.pr/free/i/w145EK

https://www.useloom.com/share/380c313a116c4eceb3f545ae413dd112

**Comment by rupok** [comment]
I have updated the form elements. We'll release the update soon. If you are using free version, you can download from Github. Make sure to rename the plugin folder to get updates properly.

**Comment by napa-web-designer** [comment]
Thanks rupok. Can you tell me what this means: "Make sure to rename the plugin folder to get updates properly".  Properly to me is that when a plugin update is due it shows in the WP dashboard and on the plugins page and I click a button and it updates. If there is something unique about how this plugin updates, could you share a link to where that is explained (to save you from re-writing here).  

Thanks again.

**Comment by rupok** [comment]
Hi there,
Sorry for the confusion. I said to rename plugin in case you download from Github. If you are downloading fro WordPress.org then no need to rename.

Thanks!
